 # array屬性

In [2]:
import numpy as np

arr1 = np.array([[1,2,3],
                [4,5,6]])

print(arr1)
print(f'維度: {arr1.ndim}')
print(f'每個維度的元素數: {arr1.shape}')
print(f'總元素個數: {arr1.size}')

[[1 2 3]
 [4 5 6]]
維度: 2
每個維度的元素數: (2, 3)
總元素個數: 6


# 生成array

In [7]:
#dtype
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]], dtype=np.int16)

print(a)
print(a.dtype)

[[1 2 3]
 [4 5 6]]
int16


In [13]:
#zeros & ones
import numpy as np

a = np.zeros((2,3))
b = np.ones((3,2))

print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [22]:
#arange & linspace
import numpy as np

a = np.arange(1,19,2).reshape(3, 3)

#等差級數
b = np.linspace(0,100,9).reshape(3,3)

print(a)
print(b)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[  0.   12.5  25. ]
 [ 37.5  50.   62.5]
 [ 75.   87.5 100. ]]


# 基礎運算

In [3]:
import numpy as np

a = np.array([10,20,30,40])
b = np.arange(4)

print(a+b)
print(b**2)
print(10*np.sin(a))

print(a<25)
print(b==2)

[10 21 32 43]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True False False]
[False False  True False]


In [7]:
#元素相乘與矩陣乘法
import numpy as np
a = np.array([[1,1],
              [0,1]])
b = np.arange(4).reshape((2,2))

c = a*b
c_dot = np.dot(a,b)
c_dot2 = a.dot(b)

print(c)
print(c_dot)
print(c_dot2)

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [17]:
#random, sum, min & max, sort
import numpy as np

a = np.random.random((2,4))

print(a)
#axis軸
print(np.sum(a, axis=0))
print(np.max(a, axis=0))
print(np.min(a, axis=1))
print(np.sort(a))

[[0.24219398 0.08160744 0.36710538 0.76826209]
 [0.14026006 0.84373374 0.09562291 0.40748843]]
[0.38245405 0.92534118 0.4627283  1.17575051]
[0.24219398 0.84373374 0.36710538 0.76826209]
[0.08160744 0.09562291]
[[0.08160744 0.24219398 0.36710538 0.76826209]
 [0.09562291 0.14026006 0.40748843 0.84373374]]


In [15]:
#arg索引, mean, median
import numpy as np

a = np.arange(2,14).reshape(3,4)

print(a)
print(np.argmax(a))
print(np.argmin(a))

print(np.mean(a))
print(a.mean())

print(np.median(a))



[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
11
0
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [22]:
#cumsum累加, diff前後差
import numpy as np

a = np.arange(2,14).reshape(3,4)

print(np.cumsum(a))
print(np.diff(a))

[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
#transpose轉置, clip限制
import numpy as np

a = np.arange(2,14).reshape(3,4)

print(np.transpose(a))
print(a.T)
print(a.T.dot(a))

print(np.clip(a, 5, 9))


[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


# array索引

In [28]:
import numpy as np

#list[2]
a = np.arange(3,15)
#row[2]
b = np.arange(3,15).reshape(3,4)

print(a[2])
print(b)
print(b[2])
print(b[2,:])
#row2,col1
print(b[2][1])
print(b[2,1])

5
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
[11 12 13 14]
12
12


In [30]:
import numpy as np

a = np.arange(3,15).reshape(3,4)
print(a)
for row in a:
    print(row)

print(a.T)
for coloum in a.T:
    print(coloum)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [38]:
import numpy as np

a = np.arange(3,15).reshape(3,4)
print(a.flatten())
for item in a.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


# array合併

In [43]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])

#stack裡面放tuple
c = np.vstack((a,b)) #vertical stack
d = np.hstack((a,b)) #horizontal stack

print(c)
print(d)
print(f'shape c:{c.shape}')
print(f'shape d:{d.shape}')

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
shape c:(2, 3)
shape d:(6,)


In [57]:
#newaxis 把橫向array立起來 
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])
print(a.T)

at = a[:, np.newaxis]
bt = b[:, np.newaxis]
print(at)
print(f'shape at{at.shape}')
ct = np.vstack((at,bt))
print(ct)
print(f'shape ct:{ct.shape}')

dt = np.hstack((at,bt))
print(dt)
print(f'shape dt:{dt.shape}')

at2 = a.reshape(3,1)
print(at2)
print(f'shape at2:{at2.shape}')

[1 1 1]
[[1]
 [1]
 [1]]
shape at(3, 1)
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
shape ct:(6, 1)
[[1 2]
 [1 2]
 [1 2]]
shape dt:(3, 2)
[[1]
 [1]
 [1]]
shape at2:(3, 1)


In [59]:
#concatenate大連接
import numpy as np

a = np.array([1,1,1])[:,np.newaxis]
b = np.array([2,2,2])[:,np.newaxis]

c = np.concatenate((a,b,a), axis=1)
print(c)

[[1 2 1]
 [1 2 1]
 [1 2 1]]
