In [10]:
# 1. Import numpy as np and see the version
import numpy as np
import pandas as pd

np.__version__

'1.24.2'

In [2]:
# 2. How to create a 1D array?
# Q. Create a 1D array of numbers from 0 to 9
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 3. How to create a boolean array?
# Q. Create a 3×3 numpy array of all True’s
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = arr % 2 == 1
arr[condition]

array([1, 3, 5, 7, 9])

In [4]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Q. Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = arr % 2 == 1
arr[condition] = -1  # sol1: boolean

np.where(arr % 2 == 1, -1, arr)  # sol2: np where(條件, 滿足, 不滿足)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# 6. How to replace items that satisfy a condition without affecting the original array?
# Q. Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
res = np.where(arr % 2 == 1, -1, arr)
print(arr, res, sep="\n")

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [9]:
# 7. How to reshape an array?
# Q. Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
res = arr.reshape(2, 5)  # sol1

res = arr.reshape(2, -1)  # sol2: col使用-1可以自動運算
print(arr, res, sep="\n")

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
# 8. How to stack two arrays vertically?
# Q. Stack arrays a and b vertically
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.concatenate([a, b], axis=0)  # sol1

np.vstack([a, b])  # sol2

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
# 9. How to stack two arrays horizontally?
# Q. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.concatenate([a, b], axis=1)  # sol1

np.hstack([a, b])  # sol2

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [18]:
# 10. How to generate custom sequences in numpy without hardcoding?
# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1, 2, 3])

result = np.hstack([np.repeat(a, 3), np.tile(a, 2)])
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3])

In [19]:
# 11. How to get the common items between two python numpy arrays?
# Q. Get the common items between a and b
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.intersect1d(a, b)

array([2, 4])

In [21]:
# 12. How to remove from one array those items that exist in another?
# Q. From array a remove all items present in array b
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
condition = ~np.isin(a,b)  # sol1
a[condition]

np.setdiff1d(a,b)

array([1, 2, 3, 4])